apiVersion: v1
kind: Service
metadata:
  name: position-service
  labels:
    app: position-service
spec:
  type: ClusterIP
  selector:
    app: position-service
  ports:
    - protocol: TCP
      port: 9116
      targetPort: 9116 