apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
  namespace: hcm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
        - name: application-service
          image: techbu/hcm-application-service:latest
          ports:
            - containerPort: 9128
          envFrom:
            - configMapRef:
                name: application-service-config
            - secretRef:
                name: application-service-secrets
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9128
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9128
            initialDelaySeconds: 30
            periodSeconds: 5 