apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: hcm
spec:
  selector:
    app: application-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9128
  type: ClusterIP 