apiVersion: v1
kind: Service
metadata:
  name: candidate-service
  labels:
    app: candidate-service
spec:
  type: ClusterIP
  selector:
    app: candidate-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 