apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-service
  labels:
    app: tenant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-service
  template:
    metadata:
      labels:
        app: tenant-service
    spec:
      containers:
        - name: tenant-service
          image: techbu/hcm-tenant-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: tenant-service-config
            - secretRef:
                name: tenant-service-secrets 