apiVersion: v1
kind: Service
metadata:
  name: tenant-service
  labels:
    app: tenant-service
spec:
  type: NodePort
  selector:
    app: tenant-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30022 