-- Transaction Management Schema
-- This table tracks all operations across HCM services

CREATE TABLE IF NOT EXISTS hcm.transaction (
    transaction_id UUID PRIMARY KEY,
    service_name VARCHAR(100) NOT NULL,
    operation_type VARCHAR(50) NOT NULL, -- CREATE, UPDATE, DELETE
    topic_name VARCHAR(200) NOT NULL,
    status VARCHAR(50) NOT NULL, -- PENDING, SUCCESS, FAILED, PROCESSING
    entity_type VARCHAR(100) NOT NULL, -- CANDIDATE, VENDOR, EMPLOYEE, etc.
    entity_id UUID, -- Primary key of the created/updated/deleted entity
    correlation_key VARCHAR(255), -- Email, ID, or other correlation key
    request_payload TEXT, -- Original request payload (JSON)
    response_payload TEXT, -- Response payload (JSON)
    error_message TEXT, -- Error message if failed
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 3,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at TIMESTAMPTZ, -- When the operation was completed
    created_by UUID NOT NULL,
    updated_by UUID NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_transaction_status ON hcm.transaction(status);
CREATE INDEX IF NOT EXISTS idx_transaction_service ON hcm.transaction(service_name);
CREATE INDEX IF NOT EXISTS idx_transaction_entity_type ON hcm.transaction(entity_type);
CREATE INDEX IF NOT EXISTS idx_transaction_correlation_key ON hcm.transaction(correlation_key);
CREATE INDEX IF NOT EXISTS idx_transaction_created_at ON hcm.transaction(created_at);
CREATE INDEX IF NOT EXISTS idx_transaction_entity_id ON hcm.transaction(entity_id);

-- Create a view for pending transactions
CREATE VIEW hcm.pending_transactions AS
SELECT * FROM hcm.transaction 
WHERE status IN ('PENDING', 'PROCESSING')
ORDER BY created_at ASC;

-- Create a view for failed transactions
CREATE VIEW hcm.failed_transactions AS
SELECT * FROM hcm.transaction 
WHERE status = 'FAILED'
ORDER BY created_at DESC;

-- Create a view for successful transactions
CREATE VIEW hcm.successful_transactions AS
SELECT * FROM hcm.transaction 
WHERE status = 'SUCCESS'
ORDER BY created_at DESC;

-- Add comments for documentation
COMMENT ON TABLE hcm.transaction IS 'Tracks all operations across HCM services for status monitoring and debugging';
COMMENT ON COLUMN hcm.transaction.transaction_id IS 'Unique transaction identifier generated by HCM Core';
COMMENT ON COLUMN hcm.transaction.service_name IS 'Name of the service that processed the operation (candidate-service, vendor-service, etc.)';
COMMENT ON COLUMN hcm.transaction.operation_type IS 'Type of operation: CREATE, UPDATE, DELETE';
COMMENT ON COLUMN hcm.transaction.topic_name IS 'Kafka topic name for the operation';
COMMENT ON COLUMN hcm.transaction.status IS 'Current status: PENDING, PROCESSING, SUCCESS, FAILED';
COMMENT ON COLUMN hcm.transaction.entity_type IS 'Type of entity being operated on: CANDIDATE, VENDOR, EMPLOYEE, etc.';
COMMENT ON COLUMN hcm.transaction.entity_id IS 'Primary key of the created/updated/deleted entity';
COMMENT ON COLUMN hcm.transaction.correlation_key IS 'Email, ID, or other key used for correlation with original request';
COMMENT ON COLUMN hcm.transaction.request_payload IS 'Original request payload as JSON';
COMMENT ON COLUMN hcm.transaction.response_payload IS 'Response payload as JSON';
COMMENT ON COLUMN hcm.transaction.error_message IS 'Error message if the operation failed';
COMMENT ON COLUMN hcm.transaction.retry_count IS 'Number of retry attempts made';
COMMENT ON COLUMN hcm.transaction.max_retries IS 'Maximum number of retry attempts allowed';
COMMENT ON COLUMN hcm.transaction.processed_at IS 'Timestamp when the operation was completed'; 