apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidate-service
  labels:
    app: candidate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candidate-service
  template:
    metadata:
      labels:
        app: candidate-service
    spec:
      containers:
        - name: candidate-service
          image: techbu/hcm-candidate-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: candidate-service-config
            - secretRef:
                name: candidate-service-secrets 