apiVersion: v1
kind: Service
metadata:
  name: candidate-service
  labels:
    app: candidate-service
spec:
  type: NodePort
  selector:
    app: candidate-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30020 