apiVersion: v1
kind: Service
metadata:
  name: jobrequisition-service
  labels:
    app: jobrequisition-service
spec:
  type: ClusterIP
  selector:
    app: jobrequisition-service
  ports:
    - protocol: TCP
      port: 9124
      targetPort: 9124 