apiVersion: v1
kind: Service
metadata:
  name: organization-service
  labels:
    app: organization-service
spec:
  type: NodePort
  selector:
    app: organization-service
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
      nodePort: 30021 